### ISSUE TITLE
No pre-compiled exe installer

### ISSUE THREAD

**Issue by EmanuelAlexandru** [brunolm/NumLock#1]
Can you upload a pre-compiled exe file so that we don't have to install the heavy Visual Studio just for this task and then uninstall it?

**Comment by EmanuelAlexandru** [comment]
Never mind, I managed to do it thanks to this answer https://superuser.com/questions/604953/how-can-i-compile-a-net-project-without-having-visual-studio-installed

**Comment by brunolm** [comment]
@ema93a if you check the release tab there's one there
https://github.com/brunolm/NumLock/releases

**Comment by EmanuelAlexandru** [comment]
> @ema93a if you check the release tab there's one there
> https://github.com/brunolm/NumLock/releases

yes, my bad, I didn't see the release tab, thanks
